### ISSUE TITLE
Getting Task Exception was never retrieved while running tsadder.py

### ISSUE THREAD

**Issue by ChazKlein** [Cryptonian007/Genisys#14]
Every time I try to execute python tsadder.py I get the following:

```
(i) Creating sessions for all accounts...
Task exception was never retrieved
future: <Task finished name='Task-19' coro=<UpdateMethods._dispatch_update() done, defined at C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\updates.py:383> exception=ConnectionError('Cannot send requests while disconnected')>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\updates.py", line 408, in _dispatch_update
    await self.get_me(input_peer=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 147, in get_me
    me = (await self(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 56, in _call
    future = sender.send(request, ordered=ordered)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\network\mtprotosender.py", line 168, in send
    raise ConnectionError('Cannot send requests while disconnected')
ConnectionError: Cannot send requests while disconnected
(i) Sessions created!
(+) Enter the exact username of the public group[Without @]
(~) Username[Eg: Techmedies_Hub]:
```

**Comment by Cryptonian007** [comment]
I am not sure about this. Probably some connection issue or a library bug. Try deleting the account and recreating sessions.
